# Generated by Django 4.1.2 on 2023-03-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
