# Generated by Django 4.1.2 on 2023-03-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="self_introduction_text",
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
