# Generated by Django 4.1.2 on 2023-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pzdrapp", "0005_folder_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partypost",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
